// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xrrvafsipefrvxnppwdx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhycnZhZnNpcGVmcnZ4bnBwd2R4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMzI2MTcsImV4cCI6MjA2NDcwODYxN30.h7TwwpmY1--w22y8NkRPc5NXnVLx3OpPddHCjHaMKUw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);